routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group([
    'middleware' => ['auth']
], function() {
    // Route::get('', [App\Http\Controllers\Backends\DashboardController::class, 'index'])->name('backends.dashboard');
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
	Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('room-types', App\Http\Controllers\Backends\RoomTypeController::class, [
        'as' => 'backends'
    ])->middleware('admin_role');

    Route::resource('rooms', App\Http\Controllers\Backends\RoomController::class, [
        'as' => 'backends'
    ]);

	Route::resource('posts', App\Http\Controllers\PostController::class);
	Route::delete('/posts/{post}/force-delete', [App\Http\Controllers\PostController::class, 'forceDestroy'])->name('posts.force_destroy');

	Route::resource('cats', App\Http\Controllers\CatController::class);
	Route::delete('/cats/{cat}/force-delete', [App\Http\Controllers\CatController::class, 'forceDestroy'])->name('cats.force_destroy');

	Route::resource('dboard', App\Http\Controllers\dboardController::class);
	Route::delete('/dboard/{dboard}/force-delete', [App\Http\Controllers\dboardController::class, 'forceDestroy'])->name('dboard.force_destroy');

	Route::resource('users', App\Http\Controllers\UserController::class);
	Route::delete('/users/{user}/force-delete', [App\Http\Controllers\UserController::class, 'forceDestroy'])->name('users.force_destroy');

    Route::get('/check-ins', [App\Http\Controllers\Backends\CheckInController::class, 'index'])->name('backends.check_ins.index');
});

/*
Route::get('/posts/{id}/show', [App\Http\Controllers\PostController::class, 'show'])->name('posts.show');;
Route::get('/posts', [App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
Route::get('/posts/create', [App\Http\Controllers\PostController::class, 'create'])->name('posts.create');;
Route::post('/posts/store', [App\Http\Controllers\PostController::class, 'store'])->name('posts.store');;
Route::get('/posts/{id}/edit', [App\Http\Controllers\PostController::class, 'edit'])->name('posts.edit');;
Route::put('/posts/{post}/update', [App\Http\Controllers\PostController::class, 'update'])->name('posts.update');;
Route::delete('/posts/{post}/delete', [App\Http\Controllers\PostController::class, 'destroy'])->name('posts.destroy');
Route::delete('/posts/{post}/force-delete', [App\Http\Controllers\PostController::class, 'forceDestroy'])->name('posts.force_destroy');

Route::get('/categories/{id}/show', [App\Http\Controllers\CategoriesController::class, 'show'])->name('categories.show');;
Route::get('/categories', [App\Http\Controllers\CategoriesController::class, 'index'])->name('categories.index');
Route::get('/categories/create', [App\Http\Controllers\CategoriesController::class, 'create'])->name('categories.create');;
Route::post('/categories/store', [App\Http\Controllers\CategoriesController::class, 'store'])->name('categories.store');;
Route::get('/categories/{id}/edit', [App\Http\Controllers\CategoriesController::class, 'edit'])->name('categories.edit');;
Route::put('/categories/{category}/update', [App\Http\Controllers\CategoriesController::class, 'update'])->name('categories.update');;
Route::delete('/categories/{category}/delete', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('categories.destroy');
Route::delete('/categories/{category}/force-delete', [App\Http\Controllers\CategoriesController::class, 'forceDestroy'])->name('categories.force_destroy');

Route::get('/pages', [App\Http\Controllers\PageController::class, 'index'])->name('pages.index');
Route::get('/pages/create', [App\Http\Controllers\PageController::class, 'create'])->name('pages.create');
Route::post('/pages/store', [App\Http\Controllers\PageController::class, 'store'])->name('pages.store');
Route::get('/pages/{id}/edit', [App\Http\Controllers\PageController::class, 'edit'])->name('pages.edit');
Route::put('/pages/{page}/update', [App\Http\Controllers\PageController::class, 'update'])->name('pages.update');
Route::delete('/pages/{page}/delete', [App\Http\Controllers\PageController::class, 'destroy'])->name('pages.destroy');
Route::delete('/pages/{page}/force-delete', [App\Http\Controllers\PageController::class, 'forceDestroy'])->name('pages.force_destroy');
*/
// Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
Route::get('/users', [App\Http\Controllers\UserController::class, 'index'])->name('users.index');
Route::get('/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');
Route::post('/users/store', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');
Route::get('/users/{id}/edit', [App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');
Route::put('/users/{user}/update', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
Route::delete('/users/{user}/delete', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroy');
Route::delete('/users/{user}/force-delete', [App\Http\Controllers\UserController::class, 'forceDestroy'])->name('users.force_destroy');


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	// Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

app/Models/Cat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cat extends Model
{
    use HasFactory, SoftDeletes;

    public $fillable = [
        'title',
    ];

    public function creator()
    {
        return $this->belongsTo(User::class,'user_id','id');
        //return $this->belongsTo(User::class, 'foreign_key', 'owner_key');
    }
}

app/Http/Controllers/CatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cat;
use Illuminate\Support\Facades\Auth;

class CatController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $cats = Cat::all();
        return view('cats.index', [
            'cats' => $cats
        ]);
    }

    public function create()
    {
      return view('cats.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);
        $cat = new Cat();
        $cat->title = $request->title;
        $cat->user_id = Auth::id();

        $cat->save();
        return redirect(route('cats.index'))->with('success','Category created successfully!');
    }

    public function show($id)
    {
        $cat = Cat::find($id);
        if (empty($cat)) {
            return redirect(route('cats.index'));
        }
        return view('cats.show')->with('cat', $cat);
    }

    public function edit(Cat $cat)
    {
           $this->authorize('updateCat', $cat);
            return view('cats.edit', [
                'cat' => $cat,
            ]);
    }

    public function update(Cat $cat, Request $request)
    {
        $this->authorize('updateCat', $cat);
        $request->validate([
            'title' => 'required',
        ]);
        $cat->title = $request->title;

        $cat->save();
        return redirect(route('cats.index'))->with('success','Category updated successfully!');
    }

    public function destroy(Cat $cat)
    {
        $this->authorize('deleteCat', $cat);
        $cat->delete();
        return redirect(route('cats.index'))->with('success','Category deleted successfully!');
    }

    public function forceDestroy(Cat $cat)
    {
        $this->authorize('deleteCat', $cat);
        $cat->forceDelete();
        return redirect(route('cats.index'))->with('success','Category deleted successfully!');
    }
}

resources/views/cats/create.blade.php
@extends('layouts.app', ['activePage' => 'category', 'titlePage' => __('Category')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Category</h4>
                            <p class="card-category"> Here you can create new category</p>
                        </div>

                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-12 text-right">
                                                <a href="{{route('cats.index')}}" class="btn btn-sm btn-primary">Back</a>
                                            </div>
                                        </div>

                                        @if (session('status'))
                                            <div class="alert alert-success" role="alert">
                                                {{ session('status') }}
                                            </div>
                                        @endif

                                        <form action="{{route('cats.store')}}" method="post">
                                            @csrf
                                            <div class="form-group">
                                                <label for="">Category Title</label>
                                                <input type="text" name="title" class="form-control">
                                            </div>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

    </div>
@endsection

resources/views/cats/edit.blade.php
@extends('layouts.app', ['activePage' => 'category', 'titlePage' => __('Category')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Category</h4>
                            <p class="card-category"> Here you can update Cagetory</p>
                        </div>

                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{route('cats.index')}}" class="btn btn-sm btn-primary">Back</a>
                                </div>
                            </div>
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                                <form action="{{ route('cats.update',$cat->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label for="">Category Title</label>
                                        <input type="text" name="title" class="form-control" value="{{$cat->title}}">
                                    </div>

                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cats/index.blade.php
@extends('layouts.app', ['activePage' => 'category', 'titlePage' => __('Category')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Category</h4>
                            <p class="card-category"> Here you can manage Category</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{route("cats.create")}}" class="btn btn-sm btn-primary">Add Category</a>
                                </div>
                            </div>

                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                        <tr>
                            {{-- <th scope="col">#</th> --}}
                            <th>Id</th>
                            <th>Title</th>
                            <th>Creator</th>
                            <th colspan="2" class="text-right">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($cats as $cat)
                            <tr>
                                {{-- <td scope="row">{{ $loop->index + 1 }}</td> --}}
                                <td>{{ $cat->id }}</td>
                                <td>{{ $cat->title }}</td>
                                <td>{{ $cat->creator->name }}</td>
                                <td width="250px;" class="td-actions text-right">
                                    <a href="{{ route('cats.show', $cat->id) }}" class="btn btn-default">Show</a>
                                    
                                    @can('updateCat', $cat)
                                        <a href="{{ route('cats.edit', $cat->id) }}"  class="btn btn-primary">Edit</a>
                                    @endcan
                                    @can('deleteCat', $cat)
                                        <a href="#" class="btn-delete-page btn btn-warning" data-form-id="frmPageDelete{{ $cat->id }}">
                                            <form id="frmPageDelete{{ $cat->id }}" action="{{ route('cats.destroy', $cat->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                            Delete
                                        </a>
                                    
                                        <a href="#" class="btn-delete-page btn btn-danger" data-form-id="frmPageForceDelete{{ $cat->id }}">
                                            <form id="frmPageForceDelete{{ $cat->id }}" action="{{ route('cats.force_destroy', $cat->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                            Force Delete
                                        </a>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $(document).ready(function() {
            // Apply onClick event to delete page
            $('.btn-delete-page').click(function() {
                if (confirm('Are you sure?')) {
                    let formId = $(this).data('form-id');
                    // Submit form
                    $('#'+ formId).submit()
                }
            });
        });
    </script>
@endpush

resources/views/cats/show.blade.php
@extends('layouts.app', ['activePage' => 'post', 'titlePage' => __('Post')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Category</h4>
                            <p class="card-category"> Here you can view category</p>
                        </div>

                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{route('cats.index')}}" class="btn btn-sm btn-primary">Back</a>
                                </div>
                            </div>
                                        @if (session('status'))
                                            <div class="alert alert-success" role="alert">
                                                {{ session('status') }}
                                            </div>
                                        @endif

                                        <h2>{{$cat->title}}</h2>
                                    </div>
                                </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
@endsection